"""empty message

Revision ID: 12de5c459955
Revises: 8bf822d2f035
Create Date: 2025-02-01 19:34:10.207232

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '12de5c459955'
down_revision = '8bf822d2f035'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_item')  # Order matters: Drop children first
    op.drop_table('order')        # Then parent tables
    op.drop_table('cart_item')   # Drop cart_item before cart
    op.drop_table('cart')        # Now you can drop cart
    op.drop_table('product')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('product_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('price', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('image', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('stock', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sku', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('collection', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('genre', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('size', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('color', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='product_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('cart_item',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cart_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['cart.id'], name='cart_item_cart_id_fkey'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name='cart_item_product_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='cart_item_pkey')
    )
    op.create_table('cart',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='cart_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='cart_pkey')
    )
    op.create_table('order',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('order_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('payment_method', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('shipping_address', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('shipping_phone', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='order_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='order_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('order_item',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], name='order_item_order_id_fkey'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name='order_item_product_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='order_item_pkey')
    )
    # ### end Alembic commands ###
