"""empty message

Revision ID: 395ba4e57fbd
Revises: d1254fa40d67
Create Date: 2025-02-11 14:32:34.095675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '395ba4e57fbd'
down_revision = 'd1254fa40d67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('talles', sa.ARRAY(sa.String()), nullable=True))
        batch_op.drop_column('talle')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('talle', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_column('talles')

    # ### end Alembic commands ###
